extra-keys = [ \
  ['ESC','/','-','HOME','UP','END','PGUP','DEL'], \
  ['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN','ENTER'] \
]
extra-keys-style = arrows-only
fullscreen = false
bell-character = ignore
